/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksUseFileUploadIndexRouteImport } from './routes/tasks/use-file-upload/index'
import { Route as TasksUploadComponentIndexRouteImport } from './routes/tasks/upload-component/index'
import { Route as TasksTupleToUnionIndexRouteImport } from './routes/tasks/tuple-to-union/index'
import { Route as TasksTupleToObjectIndexRouteImport } from './routes/tasks/tuple-to-object/index'
import { Route as TasksTupleLengthIndexRouteImport } from './routes/tasks/tuple-length/index'
import { Route as TasksTreeSelectIndexRouteImport } from './routes/tasks/tree-select/index'
import { Route as TasksTooltipIndexRouteImport } from './routes/tasks/tooltip/index'
import { Route as TasksThrottleIndexRouteImport } from './routes/tasks/throttle/index'
import { Route as TasksTabsIndexRouteImport } from './routes/tasks/tabs/index'
import { Route as TasksTableIndexRouteImport } from './routes/tasks/table/index'
import { Route as TasksStringifyIndexRouteImport } from './routes/tasks/stringify/index'
import { Route as TasksRedditThreadIndexRouteImport } from './routes/tasks/reddit-thread/index'
import { Route as TasksProgressBarIndexRouteImport } from './routes/tasks/progress-bar/index'
import { Route as TasksPickByTypeIndexRouteImport } from './routes/tasks/pick-by-type/index'
import { Route as TasksOmitByTypeIndexRouteImport } from './routes/tasks/omit-by-type/index'
import { Route as TasksMyReadonlyIndexRouteImport } from './routes/tasks/my-readonly/index'
import { Route as TasksMyPromiseIndexRouteImport } from './routes/tasks/my-promise/index'
import { Route as TasksMyPickIndexRouteImport } from './routes/tasks/my-pick/index'
import { Route as TasksMergeIndexRouteImport } from './routes/tasks/merge/index'
import { Route as TasksMathUtilsIndexRouteImport } from './routes/tasks/math-utils/index'
import { Route as TasksMakeReadonlyIndexRouteImport } from './routes/tasks/make-readonly/index'
import { Route as TasksMakeOptionalIndexRouteImport } from './routes/tasks/make-optional/index'
import { Route as TasksGptChatIndexRouteImport } from './routes/tasks/gpt-chat/index'
import { Route as TasksFirstOfArrayIndexRouteImport } from './routes/tasks/first-of-array/index'
import { Route as TasksEs5ExtendsIndexRouteImport } from './routes/tasks/es5-extends/index'
import { Route as TasksDialogIndexRouteImport } from './routes/tasks/dialog/index'
import { Route as TasksDetectTypeIndexRouteImport } from './routes/tasks/detect-type/index'
import { Route as TasksDeepEqualsIndexRouteImport } from './routes/tasks/deep-equals/index'
import { Route as TasksDebounceIndexRouteImport } from './routes/tasks/debounce/index'
import { Route as TasksAppendToObjectIndexRouteImport } from './routes/tasks/append-to-object/index'
import { Route as TasksAccordionIndexRouteImport } from './routes/tasks/accordion/index'
import { Route as TasksAbstractComponentIndexRouteImport } from './routes/tasks/abstract-component/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksUseFileUploadIndexRoute = TasksUseFileUploadIndexRouteImport.update({
  id: '/tasks/use-file-upload/',
  path: '/tasks/use-file-upload/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksUploadComponentIndexRoute =
  TasksUploadComponentIndexRouteImport.update({
    id: '/tasks/upload-component/',
    path: '/tasks/upload-component/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TasksTupleToUnionIndexRoute = TasksTupleToUnionIndexRouteImport.update({
  id: '/tasks/tuple-to-union/',
  path: '/tasks/tuple-to-union/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTupleToObjectIndexRoute = TasksTupleToObjectIndexRouteImport.update({
  id: '/tasks/tuple-to-object/',
  path: '/tasks/tuple-to-object/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTupleLengthIndexRoute = TasksTupleLengthIndexRouteImport.update({
  id: '/tasks/tuple-length/',
  path: '/tasks/tuple-length/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTreeSelectIndexRoute = TasksTreeSelectIndexRouteImport.update({
  id: '/tasks/tree-select/',
  path: '/tasks/tree-select/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTooltipIndexRoute = TasksTooltipIndexRouteImport.update({
  id: '/tasks/tooltip/',
  path: '/tasks/tooltip/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksThrottleIndexRoute = TasksThrottleIndexRouteImport.update({
  id: '/tasks/throttle/',
  path: '/tasks/throttle/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTabsIndexRoute = TasksTabsIndexRouteImport.update({
  id: '/tasks/tabs/',
  path: '/tasks/tabs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTableIndexRoute = TasksTableIndexRouteImport.update({
  id: '/tasks/table/',
  path: '/tasks/table/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksStringifyIndexRoute = TasksStringifyIndexRouteImport.update({
  id: '/tasks/stringify/',
  path: '/tasks/stringify/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRedditThreadIndexRoute = TasksRedditThreadIndexRouteImport.update({
  id: '/tasks/reddit-thread/',
  path: '/tasks/reddit-thread/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksProgressBarIndexRoute = TasksProgressBarIndexRouteImport.update({
  id: '/tasks/progress-bar/',
  path: '/tasks/progress-bar/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksPickByTypeIndexRoute = TasksPickByTypeIndexRouteImport.update({
  id: '/tasks/pick-by-type/',
  path: '/tasks/pick-by-type/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksOmitByTypeIndexRoute = TasksOmitByTypeIndexRouteImport.update({
  id: '/tasks/omit-by-type/',
  path: '/tasks/omit-by-type/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksMyReadonlyIndexRoute = TasksMyReadonlyIndexRouteImport.update({
  id: '/tasks/my-readonly/',
  path: '/tasks/my-readonly/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksMyPromiseIndexRoute = TasksMyPromiseIndexRouteImport.update({
  id: '/tasks/my-promise/',
  path: '/tasks/my-promise/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksMyPickIndexRoute = TasksMyPickIndexRouteImport.update({
  id: '/tasks/my-pick/',
  path: '/tasks/my-pick/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksMergeIndexRoute = TasksMergeIndexRouteImport.update({
  id: '/tasks/merge/',
  path: '/tasks/merge/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksMathUtilsIndexRoute = TasksMathUtilsIndexRouteImport.update({
  id: '/tasks/math-utils/',
  path: '/tasks/math-utils/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksMakeReadonlyIndexRoute = TasksMakeReadonlyIndexRouteImport.update({
  id: '/tasks/make-readonly/',
  path: '/tasks/make-readonly/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksMakeOptionalIndexRoute = TasksMakeOptionalIndexRouteImport.update({
  id: '/tasks/make-optional/',
  path: '/tasks/make-optional/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksGptChatIndexRoute = TasksGptChatIndexRouteImport.update({
  id: '/tasks/gpt-chat/',
  path: '/tasks/gpt-chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksFirstOfArrayIndexRoute = TasksFirstOfArrayIndexRouteImport.update({
  id: '/tasks/first-of-array/',
  path: '/tasks/first-of-array/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksEs5ExtendsIndexRoute = TasksEs5ExtendsIndexRouteImport.update({
  id: '/tasks/es5-extends/',
  path: '/tasks/es5-extends/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksDialogIndexRoute = TasksDialogIndexRouteImport.update({
  id: '/tasks/dialog/',
  path: '/tasks/dialog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksDetectTypeIndexRoute = TasksDetectTypeIndexRouteImport.update({
  id: '/tasks/detect-type/',
  path: '/tasks/detect-type/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksDeepEqualsIndexRoute = TasksDeepEqualsIndexRouteImport.update({
  id: '/tasks/deep-equals/',
  path: '/tasks/deep-equals/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksDebounceIndexRoute = TasksDebounceIndexRouteImport.update({
  id: '/tasks/debounce/',
  path: '/tasks/debounce/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksAppendToObjectIndexRoute =
  TasksAppendToObjectIndexRouteImport.update({
    id: '/tasks/append-to-object/',
    path: '/tasks/append-to-object/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TasksAccordionIndexRoute = TasksAccordionIndexRouteImport.update({
  id: '/tasks/accordion/',
  path: '/tasks/accordion/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksAbstractComponentIndexRoute =
  TasksAbstractComponentIndexRouteImport.update({
    id: '/tasks/abstract-component/',
    path: '/tasks/abstract-component/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tasks/abstract-component/': typeof TasksAbstractComponentIndexRoute
  '/tasks/accordion/': typeof TasksAccordionIndexRoute
  '/tasks/append-to-object/': typeof TasksAppendToObjectIndexRoute
  '/tasks/debounce/': typeof TasksDebounceIndexRoute
  '/tasks/deep-equals/': typeof TasksDeepEqualsIndexRoute
  '/tasks/detect-type/': typeof TasksDetectTypeIndexRoute
  '/tasks/dialog/': typeof TasksDialogIndexRoute
  '/tasks/es5-extends/': typeof TasksEs5ExtendsIndexRoute
  '/tasks/first-of-array/': typeof TasksFirstOfArrayIndexRoute
  '/tasks/gpt-chat/': typeof TasksGptChatIndexRoute
  '/tasks/make-optional/': typeof TasksMakeOptionalIndexRoute
  '/tasks/make-readonly/': typeof TasksMakeReadonlyIndexRoute
  '/tasks/math-utils/': typeof TasksMathUtilsIndexRoute
  '/tasks/merge/': typeof TasksMergeIndexRoute
  '/tasks/my-pick/': typeof TasksMyPickIndexRoute
  '/tasks/my-promise/': typeof TasksMyPromiseIndexRoute
  '/tasks/my-readonly/': typeof TasksMyReadonlyIndexRoute
  '/tasks/omit-by-type/': typeof TasksOmitByTypeIndexRoute
  '/tasks/pick-by-type/': typeof TasksPickByTypeIndexRoute
  '/tasks/progress-bar/': typeof TasksProgressBarIndexRoute
  '/tasks/reddit-thread/': typeof TasksRedditThreadIndexRoute
  '/tasks/stringify/': typeof TasksStringifyIndexRoute
  '/tasks/table/': typeof TasksTableIndexRoute
  '/tasks/tabs/': typeof TasksTabsIndexRoute
  '/tasks/throttle/': typeof TasksThrottleIndexRoute
  '/tasks/tooltip/': typeof TasksTooltipIndexRoute
  '/tasks/tree-select/': typeof TasksTreeSelectIndexRoute
  '/tasks/tuple-length/': typeof TasksTupleLengthIndexRoute
  '/tasks/tuple-to-object/': typeof TasksTupleToObjectIndexRoute
  '/tasks/tuple-to-union/': typeof TasksTupleToUnionIndexRoute
  '/tasks/upload-component/': typeof TasksUploadComponentIndexRoute
  '/tasks/use-file-upload/': typeof TasksUseFileUploadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tasks/abstract-component': typeof TasksAbstractComponentIndexRoute
  '/tasks/accordion': typeof TasksAccordionIndexRoute
  '/tasks/append-to-object': typeof TasksAppendToObjectIndexRoute
  '/tasks/debounce': typeof TasksDebounceIndexRoute
  '/tasks/deep-equals': typeof TasksDeepEqualsIndexRoute
  '/tasks/detect-type': typeof TasksDetectTypeIndexRoute
  '/tasks/dialog': typeof TasksDialogIndexRoute
  '/tasks/es5-extends': typeof TasksEs5ExtendsIndexRoute
  '/tasks/first-of-array': typeof TasksFirstOfArrayIndexRoute
  '/tasks/gpt-chat': typeof TasksGptChatIndexRoute
  '/tasks/make-optional': typeof TasksMakeOptionalIndexRoute
  '/tasks/make-readonly': typeof TasksMakeReadonlyIndexRoute
  '/tasks/math-utils': typeof TasksMathUtilsIndexRoute
  '/tasks/merge': typeof TasksMergeIndexRoute
  '/tasks/my-pick': typeof TasksMyPickIndexRoute
  '/tasks/my-promise': typeof TasksMyPromiseIndexRoute
  '/tasks/my-readonly': typeof TasksMyReadonlyIndexRoute
  '/tasks/omit-by-type': typeof TasksOmitByTypeIndexRoute
  '/tasks/pick-by-type': typeof TasksPickByTypeIndexRoute
  '/tasks/progress-bar': typeof TasksProgressBarIndexRoute
  '/tasks/reddit-thread': typeof TasksRedditThreadIndexRoute
  '/tasks/stringify': typeof TasksStringifyIndexRoute
  '/tasks/table': typeof TasksTableIndexRoute
  '/tasks/tabs': typeof TasksTabsIndexRoute
  '/tasks/throttle': typeof TasksThrottleIndexRoute
  '/tasks/tooltip': typeof TasksTooltipIndexRoute
  '/tasks/tree-select': typeof TasksTreeSelectIndexRoute
  '/tasks/tuple-length': typeof TasksTupleLengthIndexRoute
  '/tasks/tuple-to-object': typeof TasksTupleToObjectIndexRoute
  '/tasks/tuple-to-union': typeof TasksTupleToUnionIndexRoute
  '/tasks/upload-component': typeof TasksUploadComponentIndexRoute
  '/tasks/use-file-upload': typeof TasksUseFileUploadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tasks/abstract-component/': typeof TasksAbstractComponentIndexRoute
  '/tasks/accordion/': typeof TasksAccordionIndexRoute
  '/tasks/append-to-object/': typeof TasksAppendToObjectIndexRoute
  '/tasks/debounce/': typeof TasksDebounceIndexRoute
  '/tasks/deep-equals/': typeof TasksDeepEqualsIndexRoute
  '/tasks/detect-type/': typeof TasksDetectTypeIndexRoute
  '/tasks/dialog/': typeof TasksDialogIndexRoute
  '/tasks/es5-extends/': typeof TasksEs5ExtendsIndexRoute
  '/tasks/first-of-array/': typeof TasksFirstOfArrayIndexRoute
  '/tasks/gpt-chat/': typeof TasksGptChatIndexRoute
  '/tasks/make-optional/': typeof TasksMakeOptionalIndexRoute
  '/tasks/make-readonly/': typeof TasksMakeReadonlyIndexRoute
  '/tasks/math-utils/': typeof TasksMathUtilsIndexRoute
  '/tasks/merge/': typeof TasksMergeIndexRoute
  '/tasks/my-pick/': typeof TasksMyPickIndexRoute
  '/tasks/my-promise/': typeof TasksMyPromiseIndexRoute
  '/tasks/my-readonly/': typeof TasksMyReadonlyIndexRoute
  '/tasks/omit-by-type/': typeof TasksOmitByTypeIndexRoute
  '/tasks/pick-by-type/': typeof TasksPickByTypeIndexRoute
  '/tasks/progress-bar/': typeof TasksProgressBarIndexRoute
  '/tasks/reddit-thread/': typeof TasksRedditThreadIndexRoute
  '/tasks/stringify/': typeof TasksStringifyIndexRoute
  '/tasks/table/': typeof TasksTableIndexRoute
  '/tasks/tabs/': typeof TasksTabsIndexRoute
  '/tasks/throttle/': typeof TasksThrottleIndexRoute
  '/tasks/tooltip/': typeof TasksTooltipIndexRoute
  '/tasks/tree-select/': typeof TasksTreeSelectIndexRoute
  '/tasks/tuple-length/': typeof TasksTupleLengthIndexRoute
  '/tasks/tuple-to-object/': typeof TasksTupleToObjectIndexRoute
  '/tasks/tuple-to-union/': typeof TasksTupleToUnionIndexRoute
  '/tasks/upload-component/': typeof TasksUploadComponentIndexRoute
  '/tasks/use-file-upload/': typeof TasksUseFileUploadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tasks/abstract-component/'
    | '/tasks/accordion/'
    | '/tasks/append-to-object/'
    | '/tasks/debounce/'
    | '/tasks/deep-equals/'
    | '/tasks/detect-type/'
    | '/tasks/dialog/'
    | '/tasks/es5-extends/'
    | '/tasks/first-of-array/'
    | '/tasks/gpt-chat/'
    | '/tasks/make-optional/'
    | '/tasks/make-readonly/'
    | '/tasks/math-utils/'
    | '/tasks/merge/'
    | '/tasks/my-pick/'
    | '/tasks/my-promise/'
    | '/tasks/my-readonly/'
    | '/tasks/omit-by-type/'
    | '/tasks/pick-by-type/'
    | '/tasks/progress-bar/'
    | '/tasks/reddit-thread/'
    | '/tasks/stringify/'
    | '/tasks/table/'
    | '/tasks/tabs/'
    | '/tasks/throttle/'
    | '/tasks/tooltip/'
    | '/tasks/tree-select/'
    | '/tasks/tuple-length/'
    | '/tasks/tuple-to-object/'
    | '/tasks/tuple-to-union/'
    | '/tasks/upload-component/'
    | '/tasks/use-file-upload/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tasks/abstract-component'
    | '/tasks/accordion'
    | '/tasks/append-to-object'
    | '/tasks/debounce'
    | '/tasks/deep-equals'
    | '/tasks/detect-type'
    | '/tasks/dialog'
    | '/tasks/es5-extends'
    | '/tasks/first-of-array'
    | '/tasks/gpt-chat'
    | '/tasks/make-optional'
    | '/tasks/make-readonly'
    | '/tasks/math-utils'
    | '/tasks/merge'
    | '/tasks/my-pick'
    | '/tasks/my-promise'
    | '/tasks/my-readonly'
    | '/tasks/omit-by-type'
    | '/tasks/pick-by-type'
    | '/tasks/progress-bar'
    | '/tasks/reddit-thread'
    | '/tasks/stringify'
    | '/tasks/table'
    | '/tasks/tabs'
    | '/tasks/throttle'
    | '/tasks/tooltip'
    | '/tasks/tree-select'
    | '/tasks/tuple-length'
    | '/tasks/tuple-to-object'
    | '/tasks/tuple-to-union'
    | '/tasks/upload-component'
    | '/tasks/use-file-upload'
  id:
    | '__root__'
    | '/'
    | '/tasks/abstract-component/'
    | '/tasks/accordion/'
    | '/tasks/append-to-object/'
    | '/tasks/debounce/'
    | '/tasks/deep-equals/'
    | '/tasks/detect-type/'
    | '/tasks/dialog/'
    | '/tasks/es5-extends/'
    | '/tasks/first-of-array/'
    | '/tasks/gpt-chat/'
    | '/tasks/make-optional/'
    | '/tasks/make-readonly/'
    | '/tasks/math-utils/'
    | '/tasks/merge/'
    | '/tasks/my-pick/'
    | '/tasks/my-promise/'
    | '/tasks/my-readonly/'
    | '/tasks/omit-by-type/'
    | '/tasks/pick-by-type/'
    | '/tasks/progress-bar/'
    | '/tasks/reddit-thread/'
    | '/tasks/stringify/'
    | '/tasks/table/'
    | '/tasks/tabs/'
    | '/tasks/throttle/'
    | '/tasks/tooltip/'
    | '/tasks/tree-select/'
    | '/tasks/tuple-length/'
    | '/tasks/tuple-to-object/'
    | '/tasks/tuple-to-union/'
    | '/tasks/upload-component/'
    | '/tasks/use-file-upload/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TasksAbstractComponentIndexRoute: typeof TasksAbstractComponentIndexRoute
  TasksAccordionIndexRoute: typeof TasksAccordionIndexRoute
  TasksAppendToObjectIndexRoute: typeof TasksAppendToObjectIndexRoute
  TasksDebounceIndexRoute: typeof TasksDebounceIndexRoute
  TasksDeepEqualsIndexRoute: typeof TasksDeepEqualsIndexRoute
  TasksDetectTypeIndexRoute: typeof TasksDetectTypeIndexRoute
  TasksDialogIndexRoute: typeof TasksDialogIndexRoute
  TasksEs5ExtendsIndexRoute: typeof TasksEs5ExtendsIndexRoute
  TasksFirstOfArrayIndexRoute: typeof TasksFirstOfArrayIndexRoute
  TasksGptChatIndexRoute: typeof TasksGptChatIndexRoute
  TasksMakeOptionalIndexRoute: typeof TasksMakeOptionalIndexRoute
  TasksMakeReadonlyIndexRoute: typeof TasksMakeReadonlyIndexRoute
  TasksMathUtilsIndexRoute: typeof TasksMathUtilsIndexRoute
  TasksMergeIndexRoute: typeof TasksMergeIndexRoute
  TasksMyPickIndexRoute: typeof TasksMyPickIndexRoute
  TasksMyPromiseIndexRoute: typeof TasksMyPromiseIndexRoute
  TasksMyReadonlyIndexRoute: typeof TasksMyReadonlyIndexRoute
  TasksOmitByTypeIndexRoute: typeof TasksOmitByTypeIndexRoute
  TasksPickByTypeIndexRoute: typeof TasksPickByTypeIndexRoute
  TasksProgressBarIndexRoute: typeof TasksProgressBarIndexRoute
  TasksRedditThreadIndexRoute: typeof TasksRedditThreadIndexRoute
  TasksStringifyIndexRoute: typeof TasksStringifyIndexRoute
  TasksTableIndexRoute: typeof TasksTableIndexRoute
  TasksTabsIndexRoute: typeof TasksTabsIndexRoute
  TasksThrottleIndexRoute: typeof TasksThrottleIndexRoute
  TasksTooltipIndexRoute: typeof TasksTooltipIndexRoute
  TasksTreeSelectIndexRoute: typeof TasksTreeSelectIndexRoute
  TasksTupleLengthIndexRoute: typeof TasksTupleLengthIndexRoute
  TasksTupleToObjectIndexRoute: typeof TasksTupleToObjectIndexRoute
  TasksTupleToUnionIndexRoute: typeof TasksTupleToUnionIndexRoute
  TasksUploadComponentIndexRoute: typeof TasksUploadComponentIndexRoute
  TasksUseFileUploadIndexRoute: typeof TasksUseFileUploadIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/use-file-upload/': {
      id: '/tasks/use-file-upload/'
      path: '/tasks/use-file-upload'
      fullPath: '/tasks/use-file-upload/'
      preLoaderRoute: typeof TasksUseFileUploadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/upload-component/': {
      id: '/tasks/upload-component/'
      path: '/tasks/upload-component'
      fullPath: '/tasks/upload-component/'
      preLoaderRoute: typeof TasksUploadComponentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/tuple-to-union/': {
      id: '/tasks/tuple-to-union/'
      path: '/tasks/tuple-to-union'
      fullPath: '/tasks/tuple-to-union/'
      preLoaderRoute: typeof TasksTupleToUnionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/tuple-to-object/': {
      id: '/tasks/tuple-to-object/'
      path: '/tasks/tuple-to-object'
      fullPath: '/tasks/tuple-to-object/'
      preLoaderRoute: typeof TasksTupleToObjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/tuple-length/': {
      id: '/tasks/tuple-length/'
      path: '/tasks/tuple-length'
      fullPath: '/tasks/tuple-length/'
      preLoaderRoute: typeof TasksTupleLengthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/tree-select/': {
      id: '/tasks/tree-select/'
      path: '/tasks/tree-select'
      fullPath: '/tasks/tree-select/'
      preLoaderRoute: typeof TasksTreeSelectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/tooltip/': {
      id: '/tasks/tooltip/'
      path: '/tasks/tooltip'
      fullPath: '/tasks/tooltip/'
      preLoaderRoute: typeof TasksTooltipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/throttle/': {
      id: '/tasks/throttle/'
      path: '/tasks/throttle'
      fullPath: '/tasks/throttle/'
      preLoaderRoute: typeof TasksThrottleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/tabs/': {
      id: '/tasks/tabs/'
      path: '/tasks/tabs'
      fullPath: '/tasks/tabs/'
      preLoaderRoute: typeof TasksTabsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/table/': {
      id: '/tasks/table/'
      path: '/tasks/table'
      fullPath: '/tasks/table/'
      preLoaderRoute: typeof TasksTableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/stringify/': {
      id: '/tasks/stringify/'
      path: '/tasks/stringify'
      fullPath: '/tasks/stringify/'
      preLoaderRoute: typeof TasksStringifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/reddit-thread/': {
      id: '/tasks/reddit-thread/'
      path: '/tasks/reddit-thread'
      fullPath: '/tasks/reddit-thread/'
      preLoaderRoute: typeof TasksRedditThreadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/progress-bar/': {
      id: '/tasks/progress-bar/'
      path: '/tasks/progress-bar'
      fullPath: '/tasks/progress-bar/'
      preLoaderRoute: typeof TasksProgressBarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/pick-by-type/': {
      id: '/tasks/pick-by-type/'
      path: '/tasks/pick-by-type'
      fullPath: '/tasks/pick-by-type/'
      preLoaderRoute: typeof TasksPickByTypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/omit-by-type/': {
      id: '/tasks/omit-by-type/'
      path: '/tasks/omit-by-type'
      fullPath: '/tasks/omit-by-type/'
      preLoaderRoute: typeof TasksOmitByTypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/my-readonly/': {
      id: '/tasks/my-readonly/'
      path: '/tasks/my-readonly'
      fullPath: '/tasks/my-readonly/'
      preLoaderRoute: typeof TasksMyReadonlyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/my-promise/': {
      id: '/tasks/my-promise/'
      path: '/tasks/my-promise'
      fullPath: '/tasks/my-promise/'
      preLoaderRoute: typeof TasksMyPromiseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/my-pick/': {
      id: '/tasks/my-pick/'
      path: '/tasks/my-pick'
      fullPath: '/tasks/my-pick/'
      preLoaderRoute: typeof TasksMyPickIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/merge/': {
      id: '/tasks/merge/'
      path: '/tasks/merge'
      fullPath: '/tasks/merge/'
      preLoaderRoute: typeof TasksMergeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/math-utils/': {
      id: '/tasks/math-utils/'
      path: '/tasks/math-utils'
      fullPath: '/tasks/math-utils/'
      preLoaderRoute: typeof TasksMathUtilsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/make-readonly/': {
      id: '/tasks/make-readonly/'
      path: '/tasks/make-readonly'
      fullPath: '/tasks/make-readonly/'
      preLoaderRoute: typeof TasksMakeReadonlyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/make-optional/': {
      id: '/tasks/make-optional/'
      path: '/tasks/make-optional'
      fullPath: '/tasks/make-optional/'
      preLoaderRoute: typeof TasksMakeOptionalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/gpt-chat/': {
      id: '/tasks/gpt-chat/'
      path: '/tasks/gpt-chat'
      fullPath: '/tasks/gpt-chat/'
      preLoaderRoute: typeof TasksGptChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/first-of-array/': {
      id: '/tasks/first-of-array/'
      path: '/tasks/first-of-array'
      fullPath: '/tasks/first-of-array/'
      preLoaderRoute: typeof TasksFirstOfArrayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/es5-extends/': {
      id: '/tasks/es5-extends/'
      path: '/tasks/es5-extends'
      fullPath: '/tasks/es5-extends/'
      preLoaderRoute: typeof TasksEs5ExtendsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/dialog/': {
      id: '/tasks/dialog/'
      path: '/tasks/dialog'
      fullPath: '/tasks/dialog/'
      preLoaderRoute: typeof TasksDialogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/detect-type/': {
      id: '/tasks/detect-type/'
      path: '/tasks/detect-type'
      fullPath: '/tasks/detect-type/'
      preLoaderRoute: typeof TasksDetectTypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/deep-equals/': {
      id: '/tasks/deep-equals/'
      path: '/tasks/deep-equals'
      fullPath: '/tasks/deep-equals/'
      preLoaderRoute: typeof TasksDeepEqualsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/debounce/': {
      id: '/tasks/debounce/'
      path: '/tasks/debounce'
      fullPath: '/tasks/debounce/'
      preLoaderRoute: typeof TasksDebounceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/append-to-object/': {
      id: '/tasks/append-to-object/'
      path: '/tasks/append-to-object'
      fullPath: '/tasks/append-to-object/'
      preLoaderRoute: typeof TasksAppendToObjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/accordion/': {
      id: '/tasks/accordion/'
      path: '/tasks/accordion'
      fullPath: '/tasks/accordion/'
      preLoaderRoute: typeof TasksAccordionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/abstract-component/': {
      id: '/tasks/abstract-component/'
      path: '/tasks/abstract-component'
      fullPath: '/tasks/abstract-component/'
      preLoaderRoute: typeof TasksAbstractComponentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TasksAbstractComponentIndexRoute: TasksAbstractComponentIndexRoute,
  TasksAccordionIndexRoute: TasksAccordionIndexRoute,
  TasksAppendToObjectIndexRoute: TasksAppendToObjectIndexRoute,
  TasksDebounceIndexRoute: TasksDebounceIndexRoute,
  TasksDeepEqualsIndexRoute: TasksDeepEqualsIndexRoute,
  TasksDetectTypeIndexRoute: TasksDetectTypeIndexRoute,
  TasksDialogIndexRoute: TasksDialogIndexRoute,
  TasksEs5ExtendsIndexRoute: TasksEs5ExtendsIndexRoute,
  TasksFirstOfArrayIndexRoute: TasksFirstOfArrayIndexRoute,
  TasksGptChatIndexRoute: TasksGptChatIndexRoute,
  TasksMakeOptionalIndexRoute: TasksMakeOptionalIndexRoute,
  TasksMakeReadonlyIndexRoute: TasksMakeReadonlyIndexRoute,
  TasksMathUtilsIndexRoute: TasksMathUtilsIndexRoute,
  TasksMergeIndexRoute: TasksMergeIndexRoute,
  TasksMyPickIndexRoute: TasksMyPickIndexRoute,
  TasksMyPromiseIndexRoute: TasksMyPromiseIndexRoute,
  TasksMyReadonlyIndexRoute: TasksMyReadonlyIndexRoute,
  TasksOmitByTypeIndexRoute: TasksOmitByTypeIndexRoute,
  TasksPickByTypeIndexRoute: TasksPickByTypeIndexRoute,
  TasksProgressBarIndexRoute: TasksProgressBarIndexRoute,
  TasksRedditThreadIndexRoute: TasksRedditThreadIndexRoute,
  TasksStringifyIndexRoute: TasksStringifyIndexRoute,
  TasksTableIndexRoute: TasksTableIndexRoute,
  TasksTabsIndexRoute: TasksTabsIndexRoute,
  TasksThrottleIndexRoute: TasksThrottleIndexRoute,
  TasksTooltipIndexRoute: TasksTooltipIndexRoute,
  TasksTreeSelectIndexRoute: TasksTreeSelectIndexRoute,
  TasksTupleLengthIndexRoute: TasksTupleLengthIndexRoute,
  TasksTupleToObjectIndexRoute: TasksTupleToObjectIndexRoute,
  TasksTupleToUnionIndexRoute: TasksTupleToUnionIndexRoute,
  TasksUploadComponentIndexRoute: TasksUploadComponentIndexRoute,
  TasksUseFileUploadIndexRoute: TasksUseFileUploadIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
