/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksDetectTypeIndexRouteImport } from './routes/tasks/detect-type/index'
import { Route as TasksDebounceIndexRouteImport } from './routes/tasks/debounce/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksDetectTypeIndexRoute = TasksDetectTypeIndexRouteImport.update({
  id: '/tasks/detect-type/',
  path: '/tasks/detect-type/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksDebounceIndexRoute = TasksDebounceIndexRouteImport.update({
  id: '/tasks/debounce/',
  path: '/tasks/debounce/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tasks/debounce/': typeof TasksDebounceIndexRoute
  '/tasks/detect-type/': typeof TasksDetectTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tasks/debounce': typeof TasksDebounceIndexRoute
  '/tasks/detect-type': typeof TasksDetectTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tasks/debounce/': typeof TasksDebounceIndexRoute
  '/tasks/detect-type/': typeof TasksDetectTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tasks/debounce/' | '/tasks/detect-type/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tasks/debounce' | '/tasks/detect-type'
  id: '__root__' | '/' | '/tasks/debounce/' | '/tasks/detect-type/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TasksDebounceIndexRoute: typeof TasksDebounceIndexRoute
  TasksDetectTypeIndexRoute: typeof TasksDetectTypeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/detect-type/': {
      id: '/tasks/detect-type/'
      path: '/tasks/detect-type'
      fullPath: '/tasks/detect-type/'
      preLoaderRoute: typeof TasksDetectTypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/debounce/': {
      id: '/tasks/debounce/'
      path: '/tasks/debounce'
      fullPath: '/tasks/debounce/'
      preLoaderRoute: typeof TasksDebounceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TasksDebounceIndexRoute: TasksDebounceIndexRoute,
  TasksDetectTypeIndexRoute: TasksDetectTypeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
